### PR TITLE
Added possibility to pass custom function for element measurement

### LINKED ISSUE #20: [Feature request] option to include border in the measurement
Just like in the title. I could provide PR for this if you find this useful

### PR DESCRIPTION
**Pull request by Andarist**
closes #20

### CODE REVIEW

**Review by nkbt — APPROVED** [review]
Perfect!

**Comment by nkbt** [comment]
There are some build issues, but they are not related to this PR. Selenium needs to be updated and codecov token expired. Nevermind...

**Comment by Andarist** [comment]
Wow, that was fast :) Do you have any estimate for the new release?

**Comment by nkbt** [comment]
Need to fix the build first. Maybe today (harder on windows machine), or
tomorrow then

**Comment by Andarist** [comment]
K, keeping my fingers crossed. Cheers!

**Comment by nkbt** [comment]
+ react-height@2.2.0

**Comment by nkbt** [comment]
Hopefully builds were ok under win, and everything works just fine

**Pull request merged**
